//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ckaeyah101694fr24274_mariageEntities : DbContext
    {
        public ckaeyah101694fr24274_mariageEntities()
            : base("name=ckaeyah101694fr24274_mariageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<personne> personne { get; set; }
        public virtual DbSet<etape> etape { get; set; }
        public virtual DbSet<hebergement> hebergement { get; set; }
        public virtual DbSet<lieu> lieu { get; set; }
        public virtual DbSet<personnes_etapes> personnes_etapes { get; set; }
        public virtual DbSet<personnes_hebergements> personnes_hebergements { get; set; }
        public virtual DbSet<reponse> reponse { get; set; }
    }
}
