//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etape
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public etape()
        {
            this.etape1 = new HashSet<etape>();
            this.personnes_etapes = new HashSet<personnes_etapes>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public System.DateTime debut { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public Nullable<int> idEtapePrecedente { get; set; }
        public int idLieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etape> etape1 { get; set; }
        public virtual etape etape2 { get; set; }
        public virtual lieu lieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnes_etapes> personnes_etapes { get; set; }
    }
}
