//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hebergement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hebergement()
        {
            this.personnes_hebergements = new HashSet<personnes_hebergements>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public int idLieu { get; set; }
        public int prix { get; set; }
        public sbyte estOffert { get; set; }
        public Nullable<System.DateTime> debutOffert { get; set; }
        public Nullable<System.DateTime> finOffert { get; set; }
    
        public virtual lieu lieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnes_hebergements> personnes_hebergements { get; set; }
    }
}
