//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnes_etapes
    {
        public int idPersonne { get; set; }
        public int idEtape { get; set; }
        public string fonction { get; set; }
    
        public virtual etape etape { get; set; }
        public virtual personne personne { get; set; }
    }
}
