//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reponse
    {
        public int id { get; set; }
        public string listeParticipants { get; set; }
        public string modeTransport { get; set; }
        public string arriveeTransport { get; set; }
        public Nullable<System.DateTime> dateArrivee { get; set; }
        public string commentaires { get; set; }
        public string hotelSamediSoir { get; set; }
    }
}
